### ISSUE TITLE
Error when calling calc()

### ISSUE THREAD

**Issue by Zedwill96** [Zedwill96/PyCal#3]
Traceback (most recent call last):
  File "C:\Users\Wesley Scott\Desktop\PyCal\main.py", line 16, in <module>
    calc()
  File "C:\Users\Wesley Scott\Desktop\PyCal\funcs.py", line 14, in calc
    num1 = input("Enter first Number: ")
TypeError: 'str' object is not callable

**Comment by Zedwill96** [comment]
No longer an issue after recode
